# Homework 4.1

1. Consider the following mini collection of five sentences:

sentence 1 There is a high demand in large scale matrix factorization algorithms

sentence 2 Various softwares have been developed for non-negative matrix
factorization.

sentence 3 This is an introduction module to natural language processing.

sentence 4 Linear algebra is important in many natural language processing
problems.

sentence 5 The factorization approach can be used for processing sparse
matrix.

And consider 4 indexed terms as below:

term 1 matrix

term 2 factorization

term 3 natural language

term 4 processing

(a) Build a document-term matrix containing term counts in documents.

In [33]:
import numpy as np

sentences = [
    'There is a high demand in large scale matrix factorization algorithms',
    'Various softwares have been developed for non-negative matrix factorization.',
    'This is an introduction module to natural language processing.',
    'Linear algebra is important in many natural language processing problems.',
    'The factorization approach can be used for processing sparse matrix matrix.'
]

terms = [
    'matrix', 'factorization', 'natural language', 'processing'
]

dtm = [[0] * 4 for i in range(5)]

for i, sentence in enumerate(sentences):
    for j, term in enumerate(terms):
        dtm[i][j] = sentence.count(term)

dtm = np.array(dtm)
print(dtm)

[[1 1 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 1 1]
 [2 1 0 1]]


(b) Calculate the similarity between the following pairs of words using the cosine
function
• “matrix” and “factorization”
• “matrix” and “processing”

In [38]:
def cosine_similarity(A, B):
    return np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))

print(cosine_similarity(dtm[:, 0], dtm[:, 1]))
print(cosine_similarity(dtm[:, 0], dtm[:, 3]))

0.9428090415820635
0.47140452079103173


(c) Use the set of words {large, scale, matrix, factorization, algorithm, software, non-
negative, develop, introduction, module, natural, language, processing, linear,
algebra, sparse} as your dictionary. Build a term-context matrix by examining the
+/- 2 and repeat (b) using this matrix. In this practice, assume the context of a
target word includes this target word itself.

In [57]:
import nltk

words = {
    'large': {},
    'scale': {}, 
    'matrix': {}, 
    'factorization': {}, 
    'algorithm': {}, 
    'software': {}, 
    'non-negative': {}, 
    'develop': {}, 
    'introduction': {}, 
    'module': {}, 
    'natural': {}, 
    'language': {}, 
    'processing': {}, 
    'linear': {}, 
    'algebra': {}, 
    'sparse': {},
}

tcm = np.identity(len(words))

# for i in range(len(words)):
#     for j in range(i, len(words)):
#         if (words[i] == words[j]):
#             continue
#         for sentence in sentences:
#             if (words[i] and words[j] in sentence):
#                 print(sentence, words[i], words[j])


    # for index1, word1 in enumerate(nltk.word_tokenize(sentence.lower())):
    #     if (word1 in words):
    #         for word2 in words:
    #             if (word1 == word2):
    #                 continue
    #             if word2 in sentence.lower():
    #                 print(word1, word2)
# for i in range(len(words)):
#     for j in range(i, len(words)):
#         if (words[i] == words[j]):
#             continue
#         for sentence in sentences:
#             if (words[i] and words[j] in sentence):
#                 print(sentence, words[i], words[j])



In [70]:
for sentence in sentences:
    sentence = nltk.word_tokenize(sentence.lower())
    for i in range(len(sentence)):
        if (sentence[i] not in words):
            continue
        current_word = sentence[i]
        for j in range(max(0, i - 2), min(len(sentence), i + 3)):
            if (i == j or sentence[j] not in words):
                continue
            if (words[current_word].get(sentence[j]) == None):
                words[current_word][sentence[j]] = 1
            else:  
                words[current_word][sentence[j]] += 1

print(words)



{'large': {'scale': 2, 'matrix': 2}, 'scale': {'large': 2, 'matrix': 2, 'factorization': 2}, 'matrix': {'large': 2, 'scale': 2, 'factorization': 3, 'non-negative': 2, 'processing': 2, 'sparse': 3, 'matrix': 3}, 'factorization': {'scale': 2, 'matrix': 3, 'non-negative': 2}, 'algorithm': {}, 'software': {}, 'non-negative': {'matrix': 2, 'factorization': 2}, 'develop': {}, 'introduction': {'module': 2}, 'module': {'introduction': 2, 'natural': 2}, 'natural': {'module': 2, 'language': 3, 'processing': 3}, 'language': {'natural': 3, 'processing': 3}, 'processing': {'natural': 3, 'language': 3, 'sparse': 2, 'matrix': 2}, 'linear': {'algebra': 2}, 'algebra': {'linear': 2}, 'sparse': {'processing': 2, 'matrix': 3}}
